version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      YOUTUBE_API_KEY: <your-key>
      YOUTUBE_CHANNEL_ID: <your-channel-id>
      MONGO_DB_URI: <your-db-uri>
      ADMIN_USERNAME: <admin-username>
      ADMIN_PASSWORD: <admin-password>
