FROM maven:3.6.3-jdk-8 AS MAVEN_BUILD

COPY pom.xml /build/
COPY radio-service-api /build/radio-service-api
COPY radio-service-ui /build/radio-service-ui

WORKDIR /build/

ARG REACT_APP_SITE_URL
ARG REACT_APP_STREAM_URL
RUN mvn -DREACT_APP_SITE_URL=$REACT_APP_SITE_URL -DREACT_APP_STREAM_URL=$REACT_APP_STREAM_URL package

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=MAVEN_BUILD /build/radio-service-api/target/*.jar /app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]